services:
    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform_doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist}

    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purger\PurgerAdvert
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2017-06-06"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta}

    oc_platform.bigbrother.message_notificator:
        class: OC\PlatformBundle\BigBrother\MessageNotificator
        arguments:
            - "@request_stack"

    oc_platform.bigbrother.message_listener:
        class: OC\PlatformBundle\BigBrother\MessageListener
        arguments:
            - "@oc_platform.bigbrother.message_notificator"
        tags:
            - { name: kernel.event_listener , event: oc_platform.post_message, method: processMessage  }