<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames){
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.categories', 'cat')
            ->addSelect('cat');

        // Requête avec une expression IN
        $qb->where($qb->expr()->in('cat.name', $categoryNames));

        return $qb->getQuery()->getResult();
    }
}
